### ISSUE TITLE
Visual bug on color change

### ISSUE THREAD

**Issue by R3ngad33** [SmallTeamProjects/UOS#1]
if you change the color of the text from the menu then back out to the command line the input line color remains green until a key is hit

**Comment by Windspar** [comment]
Please confirm this commit fix it.
[Fix visual bug](https://github.com/SmallTeamProjects/UOS/commit/49bf8f4f5025f010ddf89debb15c7f57816f1ee6)
If fix please close issue.

**Comment by R3ngad33** [comment]
Working now
