### ISSUE TITLE
Highlighter Bug/Unintended minigame behavior

### ISSUE THREAD

**Issue by R3ngad33** [SmallTeamProjects/UOS#2]
Leaving then reentering the minigame renders the highlighter first.
The minigame state should be a new instance every time it is entered with no persistence between (in doing this the bug would never occur, thus wouldn't need to be fixed)

![image](https://user-images.githubusercontent.com/35588970/46642720-90114400-cb46-11e8-8b26-b0169ce9d226.png)

**Comment by Windspar** [comment]
This should fix it.
https://github.com/SmallTeamProjects/UOS/commit/fe071e56ea9f2d174768acdf06b31292fc082998
