### ISSUE TITLE
Highlighter Selection Awareness

### ISSUE THREAD

**Issue by R3ngad33** [SmallTeamProjects/UOS#3]
When highlighting a word the selection should treat it as a single selectable so moving the selector left should exit the whole word on the left, and moving right should exit the whole word on the right regardless of where the selector entered.

**Comment by Windspar** [comment]
Commit this enhancement.
https://github.com/SmallTeamProjects/UOS/commit/68125b3efa6a5676cd5ae9f3761d69eed3ab2c12
