### ISSUE TITLE
System Variables

### ISSUE THREAD

**Issue by R3ngad33** [SmallTeamProjects/UOS#5]
System color and the header and other non user specific variables should be in effect before the user logs in.

Also maybe commands that return system information. I know this is vague, but I feel it would be useful to have more commands like SHOW TIME for things like currently logged user and last login time.

**Comment by R3ngad33** [comment]
Currently if the user is not logged in the text color is green even if it has been changed in the user settings, this unintended and system color should remain consistent throughout run-time.

**Comment by R3ngad33** [comment]
'Welcome to ROBCO Industries (TM) Termlink' is currently added by terminal.py, but should be a system variable like color

**Comment by Windspar** [comment]
So user don't have there own color. It just system color.

**Comment by R3ngad33** [comment]
yes nor do they have their own headers, but they can have there own subheaders below the header
