### ISSUE TITLE
Menu Text bugs

### ISSUE THREAD

**Issue by R3ngad33** [SmallTeamProjects/UOS#6]
-Menu text without a command shows the command error message
-Menu text shouldn't be a selectable element
-Menu elements which wrap lines interfere with selection visuals
![image](https://user-images.githubusercontent.com/35588970/47239634-e3d82480-d3b3-11e8-9906-a37bcd8b65c1.png)
![image](https://user-images.githubusercontent.com/35588970/47239645-f0f51380-d3b3-11e8-962b-50b9bd5bba0e.png)

**Comment by Windspar** [comment]
> -Menu text without a command shows the command error message

Hopefully the error message is fix.

> -Menu text shouldn't be a selectable element

Yea just haven't tackle it yet. Just want to get it working first.

> -Menu elements which wrap lines interfere with selection visuals

When menu was hard coded. Didn't have to worry about this.

**Comment by R3ngad33** [comment]
The error message is fixed

**Comment by Windspar** [comment]
a042668 ignore this reference.
